### ISSUE TITLE
Broken docker image with git_recurse

### ISSUE THREAD

**Issue by bclermont** [markdownlint/markdownlint#311]
I'm trying to run docker image with the following config:

```
show_kramdown_warnings true
style all
git_recurse true
```

and I get:

```console
1| /bin/sh: can't create /home/mdl/.netrc: nonexistent directory
2 | chmod: /home/mdl/.netrc: No such file or directory
3 | + mdl .
4 | /usr/lib/ruby/gems/2.6.0/gems/mdl-0.9.0/lib/mdl/style.rb:53:in `load': undefined method `include?' for nil:NilClass (NoMethodError)
5 | from /usr/lib/ruby/gems/2.6.0/gems/mdl-0.9.0/lib/mdl.rb:25:in `run'
6 | from /usr/lib/ruby/gems/2.6.0/gems/mdl-0.9.0/bin/mdl:10:in `<top (required)>'
7 | from /usr/bin/mdl:23:in `load'
8 | from /usr/bin/mdl:23:in `<main>'
```

**Comment by lesinigo** [comment]
it is not finding the `/home/mdl`, seems like a duplicate of the already-fixed (in master, not in the published docker image) #361

**Comment by jaymzh** [comment]
In addition, git-recurse was broken and fixed in #394.

**Comment by jaymzh** [comment]
0.12.0 is out and I believe it fixes this.
